# =========================================================
# APPLICATION NAME
# =========================================================

spring.application.name=measurement


# =========================================================
# SERVER CONFIGURATION
# =========================================================

server.port=8080


# =========================================================
# H2 DATABASE CONFIGURATION
# =========================================================

spring.datasource.url=jdbc:h2:mem:quantitydb;DB_CLOSE_DELAY=-1

spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=


# =========================================================
# JPA / HIBERNATE CONFIGURATION
# =========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# H2 CONSOLE
# =========================================================

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console


# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=*


# =========================================================
# LOGGING CONFIGURATION
# =========================================================

logging.level.root=INFO

logging.level.com.quantity.measurement=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


# =========================================================
# OPTIONAL CUSTOM CONFIG
# =========================================================

repository.type=database

pool.initialSize=5

pool.maxSize=10

pool.timeout=5000